version: '3.9'
services:
  client:
    #      image: client:latest
    image: 6d66e313bd0d
    build: ./client
    ports:
      - '8081:8081'
    networks:
      #        - redis-cluster-compose
      - redis-replication
    stdin_open: true
    tty: true

  storage-service:
    #      image: storage-service:latest
    image: 019b72943e41
    build:
      context: ./storage-service
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - redis-m1
    #        - redis_1
    #        - redis_2
    #        - redis_3
    #        - redis_4
    #        - redis_5
    #        - redis_6
    #        - cluster_initiator
    networks:
      #        - redis-cluster-compose
      - redis-replication

  redis-m1:
    image: 'redis:latest'
    container_name: redis-m1
    hostname: redis-m1
    networks:
      - redis-replication
    restart: always
    ports:
      - "6380:6380"
    volumes:
#      - ./:/config/redis-1.conf
#      - ./config/redis-1.conf:/usr/local/etc/redis/redis.conf
      - ./config/redis-1.conf:/config/redis-1.conf
    command: [ "redis-server", "/config/redis-1.conf" ]
    environment:
      - REDIS_PASSWORD=admin

  redis-m2:
    image: 'redis:latest'
    container_name: redis-m2
    networks:
      - redis-replication
    restart: always
    ports:
      - "6381:6381"
    volumes:
#      - ./:/config/redis-2.conf
#      - ./config/redis-2.conf:/usr/local/etc/redis/redis.conf
       - ./config/redis-2.conf:/config/redis-2.conf
    command: [ "redis-server", "/config/redis-2.conf" ]
    environment:
      - REDIS_PASSWORD=admin

  redis-m3:
    image: 'redis:latest'
    container_name: redis-m3
    networks:
      - redis-replication
    restart: always
    ports:
      - "6382:6382"
    volumes:
#      - ./:/config/redis-3.conf
#      - ./config/redis-3.conf:/usr/local/etc/redis/redis.conf
      - ./config/redis-3.conf:/config/redis-3.conf
    command: [ "redis-server", "/config/redis-3.conf" ]
    environment:
      - REDIS_PASSWORD=admin

networks:
  redis-replication:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

#    redis_1:
#      image: 'redis:latest'
#      container_name: redis_1
#      ports:
#        - "7001:7001"
#      hostname: redis_1
#      volumes:
#        - ./config/redis-1.conf:/usr/local/etc/redis/redis.conf
#      command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
#      networks:
#        - redis-cluster-compose
#
#    redis_2:
#      image: 'redis:latest'
#      container_name: redis_2
#      hostname: redis_2
#      ports:
#        - "7002:7002"
#      volumes:
#        - ./config/redis-2.conf:/usr/local/etc/redis/redis.conf
#      command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
#      networks:
#        - redis-cluster-compose
#
#    redis_3:
#      image: 'redis:latest'
#      container_name: redis_3
#      hostname: redis_3
#      ports:
#        - "7003:7003"
#      volumes:
#        - ./config/redis-3.conf:/usr/local/etc/redis/redis.conf
#      command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
#      networks:
#        - redis-cluster-compose
#
#    redis_4:
#      image: 'redis:latest'
#      container_name: redis_4
#      hostname: redis_4
#      ports:
#        - "7004:7004"
#      volumes:
#        - ./config/redis-4.conf:/usr/local/etc/redis/redis.conf
#      command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
#      depends_on:
#        - redis_1
#      networks:
#        - redis-cluster-compose
#
#    redis_5:
#      image: 'redis:latest'
#      container_name: redis_5
#      hostname: redis_5
#      ports:
#        - "7005:7005"
#      volumes:
#        - ./config/redis-5.conf:/usr/local/etc/redis/redis.conf
#      command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
#      depends_on:
#        - redis_2
#      networks:
#        - redis-cluster-compose
#
#    redis_6:
#      image: 'redis:latest'
#      container_name: redis_6
#      hostname: redis_6
#      ports:
#        - "7006:7006"
#      volumes:
#        - ./config/redis-6.conf:/usr/local/etc/redis/redis.conf
#      command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
#      depends_on:
#        - redis_3
#      networks:
#        - redis-cluster-compose
#
#
#    cluster_initiator:
##      image: 'cluster_initiator:latest'
#      image: '313fabe8b1bd'
#      container_name: cluster_initiator
#      build:
#        context: config
#        dockerfile: Dockerfile
#      tty: true
#      ports:
#        - "6699:6699"
#      depends_on:
#        - redis_1
#        - redis_2
#        - redis_3
#        - redis_4
#        - redis_5
#        - redis_6
#      networks:
#        - redis-cluster-compose
#
#  networks:
#    redis-cluster-compose:
#      driver: bridge
