    version: '3.9'
    services:
      client:
        image: client:latest
        build: ./client
        ports:
          - '8081:8081'
#        stdin_open: true
#        tty: true

      storage-service:
        image: storage-service:latest
        build:
          context: ./storage-service
          dockerfile: Dockerfile
        ports:
          - "8181:8181"